import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useResearch } from '../context/ResearchContext';

const PaperRenderer: React.FC = () => {
    const { paper } = useResearch();

    if (!paper) {
        return (
            <div className="empty-state">
                <div className="empty-icon">
                    <span className="text-2xl">📄</span>
                </div>
                <p className="text-lg font-medium">No Paper Generated Yet</p>
                <p className="text-sm mt-2">Start a research session to generate a paper.</p>
            </div>
        );
    }

    return (
        <div id="paper-content" className="paper-content">
            {/* Title Header - Simulated */}
            <div className="paper-header">
                <h1 className="paper-title">{paper.title}</h1>
                <p className="paper-meta">Generated by Ruu Research Assistant made by Amir Hafizi</p>
                <p className="paper-date">{new Date().toLocaleDateString()}</p>
            </div>

            {/* Markdown Content */}
            <div className="paper-body">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {paper.content}
                </ReactMarkdown>
            </div>

            {/* References Section (if not already in markdown) */}
            {paper.references.length > 0 && (
                <div className="references-section">
                    <h2 className="references-title">Internet References</h2>
                    <ul className="references-list">
                        {paper.references.map((ref: string, idx: number) => (
                            <li key={idx} className="reference-item">
                                {ref}
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
};

export default PaperRenderer;
